# Generated by Django 6.0.5 on 2026-06-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор школы'), ('director', 'Директор'), ('head_teacher', 'Завуч'), ('teacher', 'Учитель'), ('parent', 'Родитель'), ('student', 'Ученик')], max_length=20, verbose_name='Роль'),
        ),
    ]
