# Generated by Django 6.0.5 on 2026-07-05 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('school', '0004_alter_academicload_options_alter_schoolgrade_options_and_more'),
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Patronymic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='structure_User_groups', related_query_name='user', to='auth.group', verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parents',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'parent'}, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Parents'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'School Administrator'), ('director', 'Director'), ('head_teacher', 'Head Teacher'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('student', 'Student')], max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='school.schoolgrade', verbose_name='School Grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='structure_User_permissions', related_query_name='user', to='auth.permission', verbose_name='User permissions'),
        ),
    ]
