# Generated by Django 6.0.5 on 2026-09-13 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_mark_unique_together_mark_lesson_and_more'),
        ('users', '0004_alter_user_groups_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers_majoring', to='students.subject', verbose_name='Major'),
        ),
    ]
