# Generated by Django 6.0.5 on 2026-06-21 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0003_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='school.schoolgrade', verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='calendarlesson',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_lessons', to='students.schedule', verbose_name='Расписание'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_groups', to='school.schoolgrade'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='students.subject', verbose_name='Предмет'),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'academic_load', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='calendarlesson',
            unique_together={('schedule', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('school_class', 'day_of_week', 'start_time')},
        ),
    ]
