# Generated by Django 6.0.5 on 2026-06-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
