# Generated by Django 6.0.5 on 2026-06-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_mark_is_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarlesson',
            name='homework_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Домашнее задание (файл)'),
        ),
        migrations.AlterField(
            model_name='calendarlesson',
            name='homework',
            field=models.TextField(blank=True, null=True, verbose_name='Домашнее задание (текст)'),
        ),
    ]
