# Generated by Django 6.0.5 on 2026-06-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_calendarlesson_homework_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarlesson',
            name='homework_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на домашнее задание'),
        ),
    ]
