# Generated by Django 6.0.5 on 2026-06-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_calendarlesson_homework_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarlesson',
            name='homework',
            field=models.TextField(blank=True, default=1, verbose_name='Домашнее задание (текст)'),
            preserve_default=False,
        ),
    ]
