# Generated by Django 6.0.5 on 2026-06-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_calendarlesson_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarlesson',
            name='homework',
            field=models.TextField(blank=True, null=True, verbose_name='Домашнее задание (текст)'),
        ),
    ]
