# Generated by Django 6.0.5 on 2026-07-05 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_academicload_options_alter_schoolgrade_options_and_more'),
        ('students', '0007_alter_calendarlesson_homework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarlesson',
            options={'verbose_name': 'Calendar Lesson', 'verbose_name_plural': 'Calendar Lessons'},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'verbose_name': 'Grade and Attendance', 'verbose_name_plural': 'Grades and Attendance'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.AlterModelOptions(
            name='studygroup',
            options={'verbose_name': 'Study Group', 'verbose_name_plural': 'Study Groups'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterField(
            model_name='calendarlesson',
            name='date',
            field=models.DateField(verbose_name='Lesson Date'),
        ),
        migrations.AlterField(
            model_name='calendarlesson',
            name='homework',
            field=models.TextField(blank=True, null=True, verbose_name='Homework (Text)'),
        ),
        migrations.AlterField(
            model_name='calendarlesson',
            name='homework_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Homework (File)'),
        ),
        migrations.AlterField(
            model_name='calendarlesson',
            name='homework_url',
            field=models.URLField(blank=True, null=True, verbose_name='Homework (URL)'),
        ),
        migrations.AlterField(
            model_name='calendarlesson',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_lessons', to='students.schedule', verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='calendarlesson',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lesson Topic'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='academic_load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='school.academicload', verbose_name='Academic Load'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='is_present',
            field=models.BooleanField(default=False, verbose_name='Is Present'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='value',
            field=models.CharField(max_length=10, verbose_name='Grade / Mark'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Classroom'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], verbose_name='Day of the Week'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='school.schoolgrade', verbose_name='School Grade'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='students.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_groups', to='school.schoolgrade', verbose_name='School Grade'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Subject Name'),
        ),
    ]
