# Generated by Django 6.0.5 on 2026-07-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_calendarlesson_options_alter_mark_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLesson',
            fields=[
            ],
            options={
                'verbose_name': 'Teacher Lesson',
                'verbose_name_plural': 'Teacher Lessons',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('students.calendarlesson',),
        ),
    ]
