# Generated by Django 6.0.5 on 2026-07-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_teacherlesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherLesson',
        ),
    ]
