# Generated by Django 6.0.5 on 2026-07-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_homeworksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='lesson_hw',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.calendarlesson'),
            preserve_default=False,
        ),
    ]
