# Generated by Django 6.0.5 on 2026-07-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_homeworksubmission_lesson_hw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworksubmission',
            name='lesson_hw',
        ),
    ]
