# Generated by Django 6.0.5 on 2026-09-13 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_academicload_options_alter_schoolgrade_options_and_more'),
        ('students', '0013_remove_homeworksubmission_lesson_hw'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mark',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks', to='students.calendarlesson'),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'academic_load', 'date', 'lesson')},
        ),
    ]
