# Generated by Django 6.0.5 on 2026-06-21 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicload',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='academic_loads', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='schoolgrade',
            name='class_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_class', to=settings.AUTH_USER_MODEL, verbose_name='Классный руководитель'),
        ),
        migrations.AddField(
            model_name='academicload',
            name='school_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_loads', to='school.schoolgrade', verbose_name='Класс'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolgrade',
            unique_together={('number', 'letter')},
        ),
        migrations.AlterUniqueTogether(
            name='academicload',
            unique_together={('school_grade', 'subject')},
        ),
    ]
