# Generated by Django 6.0.5 on 2026-07-05 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_initial'),
        ('students', '0007_alter_calendarlesson_homework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicload',
            options={'verbose_name': 'Academic Load', 'verbose_name_plural': 'Academic Loads'},
        ),
        migrations.AlterModelOptions(
            name='schoolgrade',
            options={'ordering': ['number', 'letter'], 'verbose_name': 'School Grade', 'verbose_name_plural': 'School Grades'},
        ),
        migrations.AlterField(
            model_name='academicload',
            name='school_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_loads', to='school.schoolgrade', verbose_name='School Grade'),
        ),
        migrations.AlterField(
            model_name='academicload',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_loads', to='students.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='academicload',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='academic_loads', to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='schoolgrade',
            name='class_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_class', to=settings.AUTH_USER_MODEL, verbose_name='Class Teacher'),
        ),
        migrations.AlterField(
            model_name='schoolgrade',
            name='letter',
            field=models.CharField(max_length=2, verbose_name='Grade Letter'),
        ),
        migrations.AlterField(
            model_name='schoolgrade',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Grade Number'),
        ),
    ]
