# Generated by Django 6.0.5 on 2026-06-28 09:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_initial'),
        ('structure', '0002_delete_district_delete_region'),
        ('students', '0007_alter_calendarlesson_homework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sor', 'СОР (Суммативное оценивание за раздел)'), ('soch', 'СОЧ (Суммативное оценивание за четверть)')], max_length=10)),
                ('max_ball', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='school.academicload')),
                ('calendar_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='students.calendarlesson')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_ball', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_grades', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='structure.assessmentwork')),
            ],
            options={
                'unique_together': {('work', 'student')},
            },
        ),
    ]
