# Generated by Django 6.0.5 on 2026-06-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_assessmentwork_assessmentgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentwork',
            name='academic_load',
        ),
    ]
