# Generated by Django 6.0.5 on 2026-06-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_remove_assessmentwork_academic_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentwork',
            name='max_ball',
            field=models.PositiveIntegerField(),
        ),
    ]
