# Generated by Django 6.0.5 on 2026-06-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_alter_assessmentwork_max_ball'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentgrade',
            old_name='earned_ball',
            new_name='earned_score',
        ),
        migrations.RenameField(
            model_name='assessmentwork',
            old_name='max_ball',
            new_name='max_score',
        ),
    ]
