# Generated by Django 6.0.5 on 2026-06-28 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_rename_earned_ball_assessmentgrade_earned_score_and_more'),
        ('students', '0007_alter_calendarlesson_homework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.PositiveSmallIntegerField(choices=[(1, '1 Четверть'), (2, '2 Четверть'), (3, '3 Четверть'), (4, '4 Четверть'), (5, '1 Полугодие'), (6, '2 Полугодие'), (7, 'Годовая оценка')])),
                ('total_sor_ball', models.FloatField(default=0.0, verbose_name='Сумма баллов СОР')),
                ('soch_ball', models.FloatField(default=0.0, verbose_name='Балл СОЧ')),
                ('average_percent', models.FloatField(default=0.0, verbose_name='Средний процент успеваемости')),
                ('final_mark', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговая оценка (2-5)')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_grades', to='students.schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'schedule', 'term')},
            },
        ),
    ]
