# Generated by Django 6.0.5 on 2026-06-28 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_termgrade'),
        ('students', '0007_alter_calendarlesson_homework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termgrade',
            options={'verbose_name': 'Итоговая оценка', 'verbose_name_plural': 'Итоговые оценки'},
        ),
        migrations.AlterField(
            model_name='termgrade',
            name='average_percent',
            field=models.FloatField(default=0.0, verbose_name='Средний процент'),
        ),
        migrations.AlterField(
            model_name='termgrade',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_grades', to='students.schedule', verbose_name='Предмет / Расписание'),
        ),
        migrations.AlterField(
            model_name='termgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_grades', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='termgrade',
            name='term',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Четверть'), (2, '2 Четверть'), (3, '3 Четверть'), (4, '4 Четверть'), (5, '1 Полугодие'), (6, '2 Полугодие'), (7, 'Годовая оценка')], verbose_name='Период'),
        ),
    ]
