# Generated by Django 6.0.5 on 2026-06-28 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_alter_termgrade_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Системный администратор'), ('clerk', 'Сотрудник министерства'), ('helper', 'Поддержка'), ('director', 'Директор школы'), ('teacher', 'Учитель'), ('parent', 'Родитель'), ('student', 'Ученик')], max_length=20, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='StructureClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_chat', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (Учитель/Директор)')),
            ],
            options={
                'verbose_name': 'Чат с поддержкой',
                'verbose_name_plural': 'Чаты с поддержкой',
            },
        ),
        migrations.CreateModel(
            name='SupportChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_support_chat', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (Учитель/Директор)')),
            ],
            options={
                'verbose_name': 'Чат с поддержкой',
                'verbose_name_plural': 'Чаты с поддержкой',
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='structure.supportchat', verbose_name='Чат')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
    ]
