# Generated by Django 6.0.5 on 2026-07-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0011_alter_supportchat_user_alter_supportmessage_sender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentgrade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assessmentgrade',
            name='is_absent',
            field=models.BooleanField(default=False, verbose_name='Отсутствовал (Н)'),
        ),
        migrations.AlterField(
            model_name='assessmentgrade',
            name='earned_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Набранный балл'),
        ),
    ]
