# Generated by Django 6.0.5 on 2026-07-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0012_alter_assessmentgrade_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StructureClass',
        ),
    ]
