# Generated by Django 6.0.5 on 2026-07-05 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0013_delete_structureclass'),
        ('students', '0007_alter_calendarlesson_homework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentgrade',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_grades', to='structure.assessmentwork'),
        ),
        migrations.AlterField(
            model_name='assessmentwork',
            name='calendar_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_works', to='students.calendarlesson'),
        ),
        migrations.AlterField(
            model_name='supportchat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_chats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (Учитель/Завуч/Директор)'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to='structure.supportchat', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_support_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
    ]
