# Generated by Django 6.0.5 on 2026-07-05 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('structure', '0014_alter_assessmentgrade_work_and_more'),
        ('students', '0008_alter_calendarlesson_options_alter_mark_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentgrade',
            options={'verbose_name': 'Assessment Grade', 'verbose_name_plural': 'Assessment Grades'},
        ),
        migrations.AlterModelOptions(
            name='assessmentwork',
            options={'verbose_name': 'Assessment Work', 'verbose_name_plural': 'Assessment Works'},
        ),
        migrations.AlterModelOptions(
            name='supportchat',
            options={'verbose_name': 'Support Chat', 'verbose_name_plural': 'Support Chats'},
        ),
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='termgrade',
            options={'verbose_name': 'Final Grade', 'verbose_name_plural': 'Final Grades'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='assessmentgrade',
            name='earned_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Earned Score'),
        ),
        migrations.AlterField(
            model_name='assessmentgrade',
            name='is_absent',
            field=models.BooleanField(default=False, verbose_name='Absent (Abs)'),
        ),
        migrations.AlterField(
            model_name='assessmentgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_grades', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='assessmentgrade',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='structure.assessmentwork', verbose_name='Assessment Work'),
        ),
        migrations.AlterField(
            model_name='assessmentwork',
            name='calendar_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='students.calendarlesson', verbose_name='Calendar Lesson'),
        ),
        migrations.AlterField(
            model_name='assessmentwork',
            name='max_score',
            field=models.PositiveIntegerField(verbose_name='Max Score'),
        ),
        migrations.AlterField(
            model_name='assessmentwork',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='assessmentwork',
            name='type',
            field=models.CharField(choices=[('sor', 'SAT (Summative Assessment for Term unit)'), ('soch', 'SAQ (Summative Assessment for Quarter)')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='supportchat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Activity'),
        ),
        migrations.AlterField(
            model_name='supportchat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_support_chat', to=settings.AUTH_USER_MODEL, verbose_name='User (Teacher/Administration)'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='structure.supportchat', verbose_name='Chat'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sent At'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='text',
            field=models.TextField(verbose_name='Message Text'),
        ),
        migrations.AlterField(
            model_name='termgrade',
            name='average_percent',
            field=models.FloatField(default=0.0, verbose_name='Average Percentage'),
        ),
        migrations.AlterField(
            model_name='termgrade',
            name='final_mark',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Final Grade (2-5)'),
        ),
        migrations.AlterField(
            model_name='termgrade',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_grades', to='students.schedule', verbose_name='Subject / Schedule'),
        ),
        migrations.AlterField(
            model_name='termgrade',
            name='soch_ball',
            field=models.FloatField(default=0.0, verbose_name='SAQ Score'),
        ),
        migrations.AlterField(
            model_name='termgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_grades', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='termgrade',
            name='term',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st Quarter'), (2, '2nd Quarter'), (3, '3rd Quarter'), (4, '4th Quarter'), (5, '1st Half-Year'), (6, '2nd Half-Year'), (7, 'Annual Grade')], verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='termgrade',
            name='total_sor_ball',
            field=models.FloatField(default=0.0, verbose_name='Total SAT Score'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fathers_name',
            field=models.CharField(max_length=150, verbose_name='Patronymic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='structure_user_groups', related_query_name='user', to='auth.group', verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('clerk', 'Ministry Employee'), ('helper', 'Support Staff'), ('director', 'School Director'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('student', 'Student')], max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='structure_user_permissions', related_query_name='user', to='auth.permission', verbose_name='User permissions'),
        ),
    ]
