# Generated by Django 6.0.5 on 2026-08-02 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0015_alter_assessmentgrade_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
